
services:
  backend_asiya:
    build:
      context: app
      dockerfile: Dockerfile.prod
    env_file:
      - .env.prod
    container_name: backend_asiya
    restart: always
    expose:
      - 8000
    volumes:
      - ./app:/app
      - static_volume_asiya:/app/static
      - media_volume_asiya:/app/media
    depends_on:
      database_asiya:
        condition: service_healthy
    networks:
      - proxy-net

  database_asiya:
    image: postgres:16.2-alpine3.18
    env_file: .env.prod
    restart: unless-stopped
    volumes:
      - database_storage_asiya:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    networks:
      - proxy-net

#  nginx_asiya:
#    build: nginx
#    env_file: .env.prod
#    restart: unless-stopped
#    ports:
#      - '80:80'
#      - '443:443'
#    volumes:
#      - static_volume_asiya:/app/static
#      - media_volume_asiya:/app/media
#      - certs_asiya:/etc/letsencrypt
#    depends_on:
#      - backend_asiya
#      - frontend_asiya
#
#  frontend_asiya:
#    build:
#      context: ../milcase/
#      dockerfile: Dockerfile
#    restart: always
#    depends_on:
#      - backend_asiya
#    volumes:
#      - static_volume_asiya:/frontend_static

volumes:
  database_storage_asiya:
  static_volume_asiya:
  media_volume_asiya:
  certs_asiya:

networks:
  proxy-net:
    external: true